name: CD

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  deploy:
      needs: build
      runs-on: ubuntu-latest
  
      steps:
        - name: Docker compose
          uses: appleboy/ssh-action@master
          with:
            username: ubuntu
            host: ${{ secrets.LIVE_SERVER_IP }}
            key: ${{ secrets.EC2_SSH_KEY }}
            script_stop: true
            script: |
              sudo docker stop ${{env.CURRENT_UPSTREAM}}
              sudo docker rm ${{env.CURRENT_UPSTREAM}}
              sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/sparta_ticketing_server:latest
              sudo docker-compose up -d
